version: "3.8"
services:
  user-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=gungadhisanjaya
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=user_service
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Waiting for MySQL to be ready';
      while ! nc -z db 3306; do sleep 1; done;
      echo 'MySQL ready';
      python app/run.py"
    volumes:
      - .:/app
    networks:
      - microservice-net  # <--- tambahkan ini

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservice-net  # <--- tambahkan ini

volumes:
  mysql-data:

networks:
  microservice-net:
    external: true
