version: "3.8"
services:
  user_service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=gungadhisanjaya
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword # Menambahkan password untuk user
      - DB_NAME=user_service
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service
    ports:
      - "3306:3306"
