version: "3.8"
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  user_service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=gungadhisanjaya
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=user_service
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Waiting for MySQL to be ready';
      while ! nc -z db 3306; do sleep 1; done;
      echo 'MySQL ready';
      python app/run.py"
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql # Menambahkan volume persisten untuk MySQL

volumes:
  mysql-data:
