"""delete username

Revision ID: 0e07b1674063
Revises: 5c9de1d63414
Create Date: 2025-05-08 10:02:28.041369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e07b1674063'
down_revision = '5c9de1d63414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
