"""adding face mode prefer, username

Revision ID: 5c9de1d63414
Revises: affcc4bb9e94
Create Date: 2025-05-08 09:19:30.719849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9de1d63414'
down_revision = 'affcc4bb9e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('face_model_preference', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('face_model_preference')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
