"""nambahin address

Revision ID: c00488340467
Revises: 
Create Date: 2025-05-04 09:23:36.285231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c00488340467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.drop_index('phone')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.drop_column('address')

    # ### end Alembic commands ###
