"""add is reset in password reset

Revision ID: fcc93f282324
Revises: 5ebde0ccc4d1
Create Date: 2025-05-09 15:20:08.794826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc93f282324'
down_revision = '5ebde0ccc4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reset', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_column('is_reset')

    # ### end Alembic commands ###
